config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :koszyks
  resources :przedmiots
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  
  root 'przedmiots#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/przedmiot.rb
class Przedmiot < ApplicationRecord
    before_destroy :not_referenced_by_any_line_item
    has_many :line_items
    belongs_to :user, optional: true
    mount_uploader :image, ImageUploader
    serialize :image, JSON 
    

    validates :title, :brand, :price, presence: true
    validates :size, numericality: {only_decimal: true}, length: {maximum: 4, too_long: "${count}; Zbyt dużo znaków"}
    validates :description, length: {maximum: 1000, too_long: "${count}; Zbyt dużo znaków"}
    validates :title, length: {maximum: 60, too_long: "${count}; Zbyt dużo znaków"}
    validates :price, numericality: {only_decimal: true}, length: {maximum: 7, too_long: "${count}; Zbyt dużo znaków"}

    BRAND = %w{ Nike Adidas Vans Off-white DC Jordan Converse Timberland Balenciaga Gucci Puma Asics Reebok }
    CONDITION = %w{ Nowy Znakomity Dobry Zadowalający Słaby }
    
    
    private

    def not_referenced_by_any_line_item
        unless line_items.empty?
          errors.add(:base, "Line items present")
          throw :abort
    end

   
end

end

app/controllers/przedmiots_controller.rb
class PrzedmiotsController < ApplicationController
  before_action :set_przedmiot, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index,:show]

  # GET /przedmiots or /przedmiots.json
  def index
    @przedmiots = Przedmiot.all.order("created_at desc")
  end

  # GET /przedmiots/1 or /przedmiots/1.json
  def show
  end

  # GET /przedmiots/new
  def new
    @przedmiot = current_user.przedmiots.build
  end

  # GET /przedmiots/1/edit
  def edit
  end

  # POST /przedmiots or /przedmiots.json
  def create
    @przedmiot = current_user.przedmiots.build(przedmiot_params)

    respond_to do |format|
      if @przedmiot.save
        format.html { redirect_to @przedmiot, notice: "Przedmiot został dodany pomyślnie." }
        format.json { render :show, status: :created, location: @przedmiot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @przedmiot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /przedmiots/1 or /przedmiots/1.json
  def update
    respond_to do |format|
      if @przedmiot.update(przedmiot_params)
        format.html { redirect_to @przedmiot, notice: "Przedmiot został edytowany pomyślnie." }
        format.json { render :show, status: :ok, location: @przedmiot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @przedmiot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /przedmiots/1 or /przedmiots/1.json
  def destroy
    @przedmiot.destroy
    respond_to do |format|
      format.html { redirect_to przedmiots_url, notice: "Przedmiot został zniszczony pomyślnie." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_przedmiot
      @przedmiot = Przedmiot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def przedmiot_params
      params.require(:przedmiot).permit(:brand, :model, :description, :conditon, :title, :price, :image, :size)
    end
end

app/helpers/przedmiots_helper.rb
module PrzedmiotsHelper


def przedmiot_author(przedmiot)
user_signed_in? && current_user.id == przedmiot.user_id
end

end

app/views/przedmiots/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for @przedmiot, html: { multipart: true } do |f| %>
      <%= f.error_notification %>

        <div class="columns">

          <div class="field column is-9">
            <div class="control">
              <%= f.input :title, label: "Nazwa przedmiotu: " , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field column">
            <div class="control">
              <%= f.input :price, label: "Cena:", required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

        </div>

        <div class="columns">

        <div class="field column is-9">
          <div class="control">
            <%= f.input :model, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

          <div class="field column">
            <div class="control">
              <%= f.input :size, label: "Rozmiar:", required: true, input_html: { class:"input", maxlength: 4  }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>
        </div>
        <div class="field">
          <div class="control">
            <%= f.input :description, label: "Opis", required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
          </div>
        </div>

          
              
            

        <div class="columns">
          <div class="field column is-4">
            <div class="control">
              <label class="label">Marka</label>
              <div class="control has-icons-left">
                <span class="select">
                  <%= f.input_field :brand, collection: Przedmiot::BRAND, prompt: "Wybierz markę" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-tag"></i>
                </span>
              </div>
            </div>
           </div>

          <div class="field column is-4">
            <div class="control">
              <label class="label">Stan</label>
              <div class="control has-icons-left">
                <span class="select">
                 <%= f.input_field :conditon, collection: Przedmiot::CONDITION, prompt: "Wybierz stan" %>
                </span>
                <span class="icon is-small is-left">
                  <i class="fa fa-paint-brush"></i>
                </span>
              </div>
            </div>
           </div>
         </div>

        <div class="field">
          <div class="control">
            <label class="label">Dodaj zdjęcie</label>
              <div class="file">
              <label class="file-label">
                <%= f.input :image, as: :file, input_html: { class:"file-input instrument-image" }, label: false, wrapper: false %>
                  <span class="file-cta">
                    <span class="file-icon"><i class="fa fa-upload"></i></span>
                    <span class="file-label">Wybierz plik...</span>
                  </span>
              </label>
              </div>
            </div>
          </div>
          <output id="list"></output>
        <hr />

        <div class="field is-grouped">
          <div class="control">
            <%= f.button :submit, "Dodaj przedmiot", class: 'button is-warning' %>
            <%= link_to 'Anuluj', przedmiots_path, class:'button is-light' %>
          </div>
        </div>

      <% end %>
  </div>
</div>

app/views/przedmiots/edit.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Edytuj przedmiot
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', przedmiots: @przedmiots %>
</div>

app/views/przedmiots/index.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Przeglądaj najnowsze oferty na stronie
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="instrument-index-grid pt4">
  <% @przedmiots.each do |przedmiot| %>

    <div class="instrument border-light">
      <div class="instrument-thumb">
      <%= link_to image_tag(przedmiot.image_url(:thumb)), przedmiot %>
      <% if przedmiot.conditon? %>
        <div class="condition">
          <span class="tag is-dark"><%= przedmiot.conditon %></span>
        </div>
      <% end %>
      </div>


    <div class="pa3">

      <h3 class="fw7 f4 title"><%= link_to przedmiot.title, przedmiot %></h3>

      <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(przedmiot.price,:unit => "zł " ) %></p>

      <% if przedmiot_author(przedmiot) %>
         <%= link_to 'Edytuj', edit_przedmiot_path(przedmiot), class: "button is-small" %>
         <%= link_to 'Usuń', przedmiot, method: :delete, data: { confirm: "Na pewno usunąć przedmiot?" }, class: "button is-small" %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/przedmiots/new.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Dodaj przedmiot
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', przedmiots: @przedmiot %>
</div>

app/views/przedmiots/show.html.erb
<% content_for :body_class, 'bg-light' %>

<section class="section instrument-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @przedmiot.title %></h1>

      <ul class="pv1">
        <% if @przedmiot.brand? %>
        <li class="inline-block pr3"><%= @przedmiot.brand %></li>
        <% end %>

        <li class="inline-block pr3"><%= @przedmiot.model %></li>

        <% if @przedmiot.conditon? %>
        <li class="inline-block pr3"><%= @przedmiot.conditon %></li>
        <% end %>
      </ul>

      <div class="feature-image">
        <%= image_tag(@przedmiot.image_url(:default)) %>
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4">Opis</h3>
      <%= @przedmiot.description %>


      <h3 class="subtitle is-4 pt5">Specyfikacje produktu:</h3>

      <table class="table is-narrow">
        <% if @przedmiot.conditon %>
        <tr>
          <td class="has-text-weight-bold">Stan:</td>
          <td><%= @przedmiot.conditon %></td>
        </tr>
        <% end %>
        <% if @przedmiot.brand %>
          <tr>
            <td class="has-text-weight-bold">Marka:</td>
            <td><%= @przedmiot.brand %></td>
          </tr>
        <% end %>
          <% if @przedmiot.size %>
        <tr>
          <td class="has-text-weight-bold">Rozmiar:</td>
          <td><%= @przedmiot.size %></td>
        </tr>
        <% end %>
        <tr>
          <td class="has-text-weight-bold">Model:</td>
          <td><%= @przedmiot.model %></td>
        </tr>
      </table>
    </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%= number_to_currency(@przedmiot.price,:unit => "zł ") %></h4>
        <%= button_to 'Dodaj do koszyka', line_items_path(przedmiot_id: @przedmiot, przedmiot_title: @przedmiot.title), class: 'button is-warning add-to-cart' %>
      </div>
    </div>
  </div>

</section>