config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :koszyks
  resources :przedmiots
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  
  root 'przedmiots#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/koszyk.rb
class Koszyk < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_przedmiot(przedmiot)
        
        current_item = line_items.find_by(przedmiot_id: przedmiot.id) 
        if current_item
            
        else
            current_item = line_items.build(przedmiot_id: przedmiot.id)
        end
        current_item
    end

    def total_price
        line_items.to_a.sum { |item| item.total_price }
    end

   

end

app/controllers/koszyks_controller.rb
class KoszyksController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_koszyk, only: %i[ show edit update destroy ]

  # GET /koszyks or /koszyks.json
  def index
    @koszyks = Koszyk.all
  end

  # GET /koszyks/1 or /koszyks/1.json
  def show
  end

  # GET /koszyks/new
  def new
    @koszyk = Koszyk.new
  end

  # GET /koszyks/1/edit
  def edit
  end

  # POST /koszyks or /koszyks.json
  def create
    @koszyk = Koszyk.new(koszyk_params)

    respond_to do |format|
      if @koszyk.save
        format.html { redirect_to @koszyk, notice: "Koszyk was successfully created." }
        format.json { render :show, status: :created, location: @koszyk }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @koszyk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /koszyks/1 or /koszyks/1.json
  def update
    respond_to do |format|
      if @koszyk.update(koszyk_params)
        format.html { redirect_to @koszyk, notice: "Koszyk was successfully updated." }
        format.json { render :show, status: :ok, location: @koszyk }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @koszyk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /koszyks/1 or /koszyks/1.json
  def destroy 
    @koszyk.destroy if @koszyk.id == session[:koszyk_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to przedmiots_url, notice: "Koszyk został wyczyszczony." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_koszyk
      @koszyk = Koszyk.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def koszyk_params
      params.fetch(:koszyk, {})
    end

    def invalid_cart
      logger.error "Próba dostania się do niewłaściwego koszyka. #{params[:id]}"
      redirect_to root_path, notice: "Ten koszyk nie istnieje."
    
    end








end

app/helpers/koszyks_helper.rb
module KoszyksHelper
end

app/views/koszyks/_form.html.erb
<%= simple_form_for(@koszyk) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/koszyks/edit.html.erb
<h1>Editing Koszyk</h1>

<%= render 'form', koszyk: @koszyk %>

<%= link_to 'Show', @koszyk %> |
<%= link_to 'Back', koszyks_path %>

app/views/koszyks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Koszyks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @koszyks.each do |koszyk| %>
      <tr>
        <td><%= link_to 'Show', koszyk %></td>
        <td><%= link_to 'Edit', edit_koszyk_path(koszyk) %></td>
        <td><%= link_to 'Destroy', koszyk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Koszyk', new_koszyk_path %>

app/views/koszyks/new.html.erb
<h1>New Koszyk</h1>

<%= render 'form', koszyk: @koszyk %>

<%= link_to 'Back', koszyks_path %>

app/views/koszyks/show.html.erb
<div class="keep-shopping pv1 mt4 has-text-right">
  <%= link_to 'Kontynuuj zakupy', przedmiots_path, class: 'button is-warning' %>
  <%= %>
</div>
<hr />
<section class="section">
  <%= render(@koszyk.line_items) %>

  <div class="columns">
    <div class="column">
      <%= button_to 'Wyczyść koszyk', @koszyk, method: :delete, data: { confirm: "Na pewno usunąć koszyk? " }, class: "button is-danger" %>
    </div>
    <div class="column total has-text-right">
      <h4 class="title is-4">
        <span class="f5 has-text-grey">Suma: </span> <%= number_to_currency(@koszyk.total_price,:unit => "zł ") %>
      </h4>
        <%= link_to 'Kontynuuj transakcję', new_order_path(totalPrice: @koszyk.total_price), class: "button is-info" %>
     
    </div>
  </div>
</section>