config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :koszyks
  resources :przedmiots
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  
  root 'przedmiots#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

    DOSTAWA = ["Paczkomat InPost - 8 zł", "Pocza Polska - 13 zł","Kurier - 18 zł", "Kurier pobranie - 23 zł"]

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: "Zamówienie zostało złożone pomyślnie można opuscić stronę." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Zamówienie zostało usunięte pomyślnie." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:imie, :nazwisko, :miasto, :ulica, :kodpocztowy, :telefon, :dostawa)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

     <%= f.input :imie, label: 'Imię:', input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }, required: true %> 

    <%= f.input :nazwisko,label: 'Nazwisko:', input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }, required: true %>
    
    <%= f.input :miasto,label: 'Miasto:', input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }, required: true %> 
  
    <%= f.input :ulica,label: 'Ulica:', input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }, required: true %> 
    
    <%= f.input :kodpocztowy,label: 'Kod pocztowy:', input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }, required: true%> 
    
    <%= f.input :telefon,label: 'Numer telefonu:', input_html: { class: "input"}, wrapper: false, label_html: { class: "label" }, required: true  %> 
          
    <div class="control">
      <label class="label">Dostawa</label>
          <div class="control has-icons-left">
            <span class="select">
              <%= f.input_field :dostawa, collection: Order::DOSTAWA, prompt: "Wybierz formę dostawy", required: true %>
            </span>
            <span class="icon is-small is-left">
              <i class="fa fa-truck"></i>
            </span>
            </div>
    </div>
    <div class="is-size-3">
    <% total_price = params[:totalPrice] %>
    <p>Do zapłaty: <%= total_price %> zł + dostawa </p>
    </div>

    <div>
    
    
    </div>
           
  <div class="form-actions" style="padding-top: 1rem">
    <%= f.button :submit, 'Zamów', class: 'button is-primary' %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1 class="is-size-2">Zamówienia</h1>
<hr>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
      <p class="is-size-4">
        <td>Zamówienie numer: <%= order.id %>,</td>
        <td>złożone przez: <%= order.imie %> <%= order.nazwisko %>,</td>
        <td>numer telefonu: <%= order.telefon %></td>
      </p>
        <td><%= link_to 'Pokaż zamówienie', order, class: "button is-info" %></td>
        <td><%= link_to 'Usuń zamówienie', order, method: :delete, data: { confirm: 'Na pewno usunąć zamówienie?' }, class: "button is-danger" %></td>
      </tr>
      <hr>
    <% end %>
  </tbody>
</table>

<br>
<script>

app/views/orders/new.html.erb
<h1 class='is-size-1'>Zamówienie</h1>

<ul class="steps is-narrow is-medium is-centered has-content-centered">
      <li class="steps-segment">
       
      <li class="steps-segment">
        <i class="has-text-dark">
          <span class="steps-marker">
            <span class="icon">
              <i class="fa fa-user"></i>
            </span>
          </span>
          <div class="steps-content">
            <p class="heading">Dane klienta:</p>
          </div>
        </i>
      

<%= render 'form', order: @order %>

<%= link_to 'Wróć do koszyka', koszyk_path(@koszyk.id) %>

app/views/orders/show.html.erb
<h1 class="is-size-2">Zamówienie zostanie wysłane na podane dane:</h1>
<table class="table is-narrow">
        <tr>
          <td class="has-text-weight-bold">Imię:</td>
          <td><%= @order.imie %></td>
        </tr>
          <tr>
            <td class="has-text-weight-bold">Nazwisko:</td>
            <td><%= @order.nazwisko %></td>
          </tr>
        <tr>
          <td class="has-text-weight-bold">Miasto:</td>
          <td><%= @order.miasto %></td>
        </tr>
        <tr>
          <td class="has-text-weight-bold">Ulica:</td>
          <td><%= @order.ulica %></td>
        </tr>
         <tr>
          <td class="has-text-weight-bold">Kod pocztowy:</td>
          <td><%= @order.kodpocztowy %></td>
        </tr>
         <tr>
          <td class="has-text-weight-bold">Numer telefonu:</td>
          <td><%= @order.telefon %></td>
        </tr>
      </table>
       <%= link_to 'Wróć na stronę główną', root_path, class: "button is-info" %>
    </div>
    </div>